
package org.apache.torque.tutorial.om;
/**
 * Tabla de Candidatos
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Nov 27 10:46:13 CST 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class CandidatoPeerImpl
    extends org.apache.torque.tutorial.om.BaseCandidatoPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1417106773631L;



}
