package org.apache.torque.tutorial.om;


/**
 * Maps ResultSet rows into Candidato objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Nov 27 10:46:15 CST 2014]
 *
 */
public class CandidatoRecordMapper extends BaseCandidatoRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1417106775051L;



}
