package org.apache.torque.tutorial.om;

/**
 * Tabla de Candidatos
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Nov 27 10:46:13 CST 2014]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class CandidatoPeer
    extends org.apache.torque.tutorial.om.BaseCandidatoPeer
{

}
