package org.apache.torque.tutorial.om;


/**
 * Tabla de Usuarios
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Nov 27 10:46:11 CST 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class Usuario
    extends org.apache.torque.tutorial.om.BaseUsuario
{
    /** Serial version */
    private static final long serialVersionUID = 1417106771603L;



}
