package org.apache.torque.tutorial.om;


/**
 * Maps ResultSet rows into Usuario objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Nov 27 10:46:15 CST 2014]
 *
 */
public class UsuarioRecordMapper extends BaseUsuarioRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1417106775067L;



}
